version: "3"

services:
  app:
    build: ./docker/.
    container_name: app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./docker/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'

  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
