services:
  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME:-app}_nginx
    ports:
      - "${HTTP_PORT:-8888}:80"
      - "${HTTPS_PORT:-8543}:443"
    volumes:
      - ../../../.:/var/www/html:delegated
      - ../services/nginx/config/config.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - backend

networks:
  backend:
    driver: bridge
