services:
  mariadb:
    image: mariadb:10.11
    container_name: ${PROJECT_NAME_SNAKE_CASE}_database
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ../mariadb/storage/data:/var/lib/mariadb
      - ../mariadb/config/initdb.d:/docker-entrypoint-initdb.d
      - ../mariadb/config/conf.d:/etc/mariadb/conf.d:ro
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

volumes:
  data:

networks:
  backend: