version: '3.8'

services:
  mysql:
      image: mysql:8.0
      container_name: ${PROJECT_NAME:-app}-mysql
      restart: unless-stopped
      ports:
        - "${MYSQL_PORT:-3306}:3306"
      volumes:
        - mysql_data:/var/lib/mysql
        - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
        - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
        MYSQL_USER: ${MYSQL_USER:-app}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
      networks:
        - backend
      command: --default-authentication-plugin=mysql_native_password
